### ISSUE TITLE
Handling Custom Versions of Ember

### ISSUE THREAD

**Issue by blimmer** [rwjblue/ember-cli-version-checker#17]
I'm stuck on 1.12 on a project and have a custom patched version of Ember that looks like this in my bower.json.

```json
"ember": "Ibotta/ember#f98a92242cf5d0635c07fc6a55d10d22322a2dce",
```

When ember-cli-version-checker encounters this, I get this exception:

```bash
Invalid Version: 1.12.2.f2794747
TypeError: Invalid Version: 1.12.2.f2794747
  at new SemVer (/Users/blimmer/code/webapps/ibotta-web/node_modules/ember
-get-helper/node_modules/ember-cli-version-checker/node_modules/semver/sem
ver.js:295:11)
  at compare (/Users/blimmer/code/webapps/ibotta-web/node_modules/ember-get-helper/node_modules/ember-cli-version-checker/node_modules/semver/semver.js:571:10)
  at Function.lt (/Users/blimmer/code/webapps/ibotta-web/node_modules/ember-get-helper/node_modules/ember-cli-version-checker/node_modules/semver/semver.js:605:10)
  at DependencyVersionChecker.(anonymous function) [as lt] (/Users/blimmer/code/webapps/ibotta-web/node_modules/ember-get-helper/node_modules/ember-cli-version-checker/index.js:68:26)
  at Class.module.exports.treeFor (/Users/blimmer/code/webapps/ibotta-web/node_modules/ember-get-helper/index.js:15:31)
  at EmberApp.<anonymous> (/Users/blimmer/code/webapps/ibotta-web/node_modules/ember-cli/lib/broccoli/ember-app.js:342:20)
  at Array.map (native)
  at EmberApp.addonTreesFor (/Users/blimmer/code/webapps/ibotta-web/node_modules/ember-cli/lib/broccoli/ember-app.js:340:30)
  at EmberApp._processedAppTree (/Users/blimmer/code/webapps/ibotta-web/node_modules/ember-cli/lib/broccoli/ember-app.js:530:25)
  at EmberApp.appAndDependencies (/Users/blimmer/code/webapps/ibotta-web/node_modules/ember-cli/lib/broccoli/ember-app.js:807:24)
  at EmberApp.javascript (/Users/blimmer/code/webapps/ibotta-web/node_modules/ember-cli/lib/broccoli/ember-app.js:882:34)
  at EmberApp.toArray (/Users/blimmer/code/webapps/ibotta-web/node_modules/ember-cli/lib/broccoli/ember-app.js:1250:10)
  at EmberApp.toTree (/Users/blimmer/code/webapps/ibotta-web/node_modules/ember-cli/lib/broccoli/ember-app.js:1272:30)
```

is there a workaround?

**Comment by jamesarosen** [comment]
Possibly a duplicate of rwjblue/ember-cli-version-checker#13
